
import LINKS from 'utils/constants/links';

const FOOTER_MENU = [
  {
    HREF: LINKS.HOME.HREF,
    TITLE: LINKS.HOME.TITLE
  },
  {
    HREF: LINKS.MARKETPLACE.HREF,
    TITLE: LINKS.MARKETPLACE.TITLE
  },
  {
    HREF: LINKS.CREATE_NFT.HREF,
    TITLE: LINKS.CREATE_NFT.TITLE
  }
]

export default FOOTER_MENU