
const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
const RESET = 'RESET'
const SET_GAME_SPACE = 'SET_GAME_SPACE'
const SET_CONNECT_STATUS = 'SET_CONNECT_STATUS'
const SET_CONNECT_ENV_ID = 'SET_CONNECT_ENV_ID'
const SET_COMMANDS = 'SET_COMMANDS'
const SET_GAME_LOGS = 'SET_GAME_LOGS'
const SET_IS_LOG = 'SET_IS_LOG'
const SET_GRAPH_LINKS = 'SET_GRAPH_LINKS'
const SET_GRAPH_NODES = 'SET_GRAPH_NODES'
const SET_MESSAGES = 'SET_MESSAGES'
const SET_ACTORS = 'SET_ACTORS'
const SET_CHAT_SPACES = 'SET_CHAT_SPACES'
const FETCH_USER_GAME_SPACES = 'FETCH_USER_GAME_SPACES'
const FETCH_READABLE_GAME_SPACES = 'FETCH_READABLE_GAME_SPACES'
const FETCH_USER_RESOURCES = 'FETCH_USER_RESOURCES'

export {
  SET_LOADING_STATUS,
  SET_CURRENT_USER,
  SET_ACCESS_TOKEN,
  RESET,
  SET_GAME_SPACE,
  SET_CONNECT_STATUS,
  SET_CONNECT_ENV_ID,
  SET_COMMANDS,
  SET_IS_LOG,
  SET_GAME_LOGS,
  SET_GRAPH_LINKS,
  SET_GRAPH_NODES,
  SET_MESSAGES,
  SET_ACTORS,
  SET_CHAT_SPACES,
  FETCH_USER_GAME_SPACES,
  FETCH_READABLE_GAME_SPACES,
  FETCH_USER_RESOURCES
};
