
const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_ACCOUNT_RS = 'SET_ACCOUNT_RS'

export {
  SET_LOADING_STATUS,
  SET_CURRENT_USER,
  SET_ACCOUNT_RS,
};
